name: 'Deployment'

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            message:
                description: 'Commit message'
                required: false
                type: string
            author:
                description: 'Commit author'
                required: false
                type: string

env:
    USERAGENT: ${{ secrets.USERAGENT }}
    SESSDATA: ${{ secrets.SESSDATA }}
    COMMIT_MESSAGE: ${{ github.event.head_commit.message || inputs.message }}
    COMMIT_AUTHOR: ${{ github.event.head_commit.author.username || inputs.author || github.actor }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
            - name: Set Node Version
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Deploy Script
              run: pnpm run deploy --message="$COMMIT_MESSAGE" --author="$COMMIT_AUTHOR"
